{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_003.Test_Credence_003 object at 0x0000023FAD34A490>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file_003.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "e4a50ca1-5a6a-4a31-855d-1335027e4825-attachment.txt", "type": "text/plain"}], "start": 1690770344833, "stop": 1690770344834, "uuid": "a7be5e9d-2601-4add-b63d-233f0234b8df", "historyId": "1da0023011657c42a38b1de108e70725", "testCaseId": "1da0023011657c42a38b1de108e70725", "fullName": "test_file_003.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file_003"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "DESKTOP-USE2H4O"}, {"name": "thread", "value": "6988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_003"}]}